name: snu_graphics
channels:
  - defaults
dependencies:
  - python>=3.8
  - numpy==2.2.4
  - scipy==1.15.2
  - numpy==2.2.5
  - pillow==11.1.0
  - tqdm==4.67.1
  - pip
  - pip:
      - pyglet>=2.1.0
      # - another-pip-package

# scipy
# numpy